apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-api
  namespace: webhook-platform
  labels:
    app.kubernetes.io/name: webhook-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhook-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/coolspartak9819-rgb/webhook-delivery-platform:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 10
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 500m, memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-api
  namespace: webhook-platform
spec:
  selector:
    app.kubernetes.io/name: webhook-api
  ports:
    - name: http
      port: 80
      targetPort: http
