services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: queuelens
      POSTGRES_USER: queuelens
      POSTGRES_PASSWORD: queuelens
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U queuelens -d queuelens"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      args:
        SERVICE: api
    environment:
      DATABASE_URL: postgres://queuelens:queuelens@postgres:5432/queuelens
      REDIS_ADDR: redis:6379
      QUEUE_STREAM: jobs
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: job-events
      API_KEY: ${API_KEY:-}
    ports:
      - "8083:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  worker:
    build:
      context: .
      args:
        SERVICE: worker
    environment:
      DATABASE_URL: postgres://queuelens:queuelens@postgres:5432/queuelens
      REDIS_ADDR: redis:6379
      QUEUE_STREAM: jobs
      WORKER_GROUP: queuelens-workers
      WORKER_NAME: worker-1
      MAX_ATTEMPTS: "3"
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: job-events
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  dispatcher:
    build:
      context: .
      args:
        SERVICE: dispatcher
    environment:
      DATABASE_URL: postgres://queuelens:queuelens@postgres:5432/queuelens
      REDIS_ADDR: redis:6379
      QUEUE_STREAM: jobs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api

  kafka:
    image: apache/kafka:4.0.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  postgres-data:
